export enum PaymentValidationStage {
  REQUEST = "REQUEST",
  RESERVATION = "RESERVATION",
  PRICING = "PRICING",
  SETTLEMENT_READINESS = "SETTLEMENT_READINESS",
  GATEWAY_READINESS = "GATEWAY_READINESS",
}
