export enum ExperienceType {
  WINE = "WINE",
  RESTAURANT = "RESTAURANT",
  ACTIVITY = "ACTIVITY",
  SAFARI = "SAFARI",
  CULTURAL = "CULTURAL",
  SCENIC = "SCENIC",
  TRANSFER = "TRANSFER",
  EVENT = "EVENT",
}