export enum AccommodationInventoryValidationErrorCode {
  MISSING_IDENTIFIER,
  MISSING_CHECK_IN,
  MISSING_CHECK_OUT,
  INVALID_DATE_RANGE,
  INVALID_ADULT_COUNT,
  INVALID_CHILD_COUNT,
  INVALID_ROOM_COUNT,
  MISSING_REQUEST_ID,
  MISSING_SOURCE,
  MISSING_TIMESTAMP,
}