export enum JourneyValidationErrorCode {
  INVALID_QUERY,
  MISSING_CONTEXT,
  INVALID_JOURNEY_TYPE,
  INVALID_STRATEGY,
  INVALID_DESTINATION,
  INVALID_DURATION,
  INVALID_TRAVELLER_RULES,
  INVALID_AGGREGATE,
  MISSING_IDENTITY,
  INVALID_CLASSIFICATION,
  UNKNOWN,
}