export enum PaymentEventType {
  PAYMENT_CREATED = "PAYMENT_CREATED",
  AUTHORIZATION_REQUESTED = "AUTHORIZATION_REQUESTED",
  AUTHORIZATION_APPROVED = "AUTHORIZATION_APPROVED",
  AUTHORIZATION_DECLINED = "AUTHORIZATION_DECLINED",
  CAPTURE_REQUESTED = "CAPTURE_REQUESTED",
  CAPTURE_COMPLETED = "CAPTURE_COMPLETED",
  SETTLEMENT_COMPLETED = "SETTLEMENT_COMPLETED",
  REFUND_REQUESTED = "REFUND_REQUESTED",
  REFUND_COMPLETED = "REFUND_COMPLETED",
}
