export enum InvoiceValidationStage {
  REQUEST = "REQUEST",
  RESERVATION = "RESERVATION",
  COMMERCIAL = "COMMERCIAL",
  FINANCIAL_INTEGRITY = "FINANCIAL_INTEGRITY",
  LIFECYCLE_READINESS = "LIFECYCLE_READINESS",
}