export enum PaymentRequiredAction {
  STRONG_CUSTOMER_AUTHENTICATION = "STRONG_CUSTOMER_AUTHENTICATION",
  MANUAL_APPROVAL = "MANUAL_APPROVAL",
  FRAUD_REVIEW = "FRAUD_REVIEW",
  IDENTITY_VERIFICATION = "IDENTITY_VERIFICATION",
  COMPLIANCE_REVIEW = "COMPLIANCE_REVIEW",
}
