export enum InvoiceRequiredAction {
  MANUAL_APPROVAL = "MANUAL_APPROVAL",
  CUSTOMER_VERIFICATION = "CUSTOMER_VERIFICATION",
  PAYMENT_REVIEW = "PAYMENT_REVIEW",
  CANCELLATION_REVIEW = "CANCELLATION_REVIEW",
  ACCOUNTING_REVIEW = "ACCOUNTING_REVIEW",
  FINANCIAL_REVIEW = "FINANCIAL_REVIEW",
}