export enum AccommodationContentSource {
  HOMEPAGE = "HOMEPAGE",
  PACKAGE_BUILDER = "PACKAGE_BUILDER",
  PACKAGE_DETAILS = "PACKAGE_DETAILS",
  ADMIN = "ADMIN",
  API = "API",
  INTERNAL = "INTERNAL",
}