export enum PricingCalculatorStage {
  ACCOMMODATION = "ACCOMMODATION",
  EXPERIENCE = "EXPERIENCE",
  PROMOTION = "PROMOTION",
  DISCOUNT = "DISCOUNT",
  TAX = "TAX",
  MARKUP = "MARKUP",
  COMMISSION = "COMMISSION",
  TOTAL = "TOTAL",
}
