export const problemDetailsSchema = {
	name: "ProblemDetails",
	type: "object",
	properties: {
		type: {
			type: "string",
			description: "A URI reference that identifies the problem type.",
		},
		title: {
			type: "string",
			description: "A short, human-readable summary of the problem type.",
		},
		status: {
			type: "integer",
			description: "The HTTP status code generated by the origin server.",
		},
		detail: {
			type: "string",
			description: "A human-readable explanation specific to this occurrence of the problem.",
		},
		instance: {
			type: "string",
			description: "A URI reference that identifies the specific occurrence of the problem.",
		},
		timestamp: {
			type: "string",
			format: "date-time",
			description: "The time at which the problem occurred.",
		},
	},
	required: ["type", "title", "status", "detail", "instance", "timestamp"],
};
