export enum AccommodationProviderCapabilityType {
  SEARCH = "SEARCH",
  DETAILS = "DETAILS",
  AVAILABILITY = "AVAILABILITY",
  CONTENT = "CONTENT",
  IMAGES = "IMAGES",
  RATES = "RATES",
  REVALIDATION = "REVALIDATION",
  BOOKING = "BOOKING",
  CANCELLATION = "CANCELLATION",
}
